<?php
session_start(); if(!isset($_SESSION['divisi'])||$_SESSION['divisi']!=='akunting'){header('Location: ../index.php');exit;} require_once '../config/database.php';
$periode=$_GET['periode']??'bulan'; $valid=['hari','minggu','bulan','tahun']; if(!in_array($periode,$valid,true))$periode='bulan';
$where="t.created_at >= DATE_TRUNC('month',CURRENT_DATE) AND t.created_at < DATE_TRUNC('month',CURRENT_DATE)+INTERVAL '1 month'"; if($periode==='hari')$where="t.created_at>=CURRENT_DATE AND t.created_at<CURRENT_DATE+INTERVAL '1 day'"; elseif($periode==='minggu')$where="t.created_at>=DATE_TRUNC('week',CURRENT_DATE) AND t.created_at<DATE_TRUNC('week',CURRENT_DATE)+INTERVAL '1 week'"; elseif($periode==='tahun')$where="t.created_at>=DATE_TRUNC('year',CURRENT_DATE) AND t.created_at<DATE_TRUNC('year',CURRENT_DATE)+INTERVAL '1 year'";
$sql="SELECT k.id,k.barcode_uid,k.nama_lengkap,k.grup_shift,COALESCE(SUM(t.berat_kg),0) total_kg,COALESCE(SUM(t.total_upah),0) upah_produksi FROM karyawan k LEFT JOIN transaksi_timbang t ON t.karyawan_id=k.id AND $where WHERE k.status_aktif=true GROUP BY k.id,k.barcode_uid,k.nama_lengkap,k.grup_shift ORDER BY k.nama_lengkap"; $rows=$pdo->query($sql)->fetchAll();
foreach($rows as &$r){$s=$pdo->prepare("SELECT COALESCE(SUM(total_upah_lembur),0) FROM absensi_lembur WHERE karyawan_id=? AND waktu_mulai >= DATE_TRUNC('month',CURRENT_DATE) AND waktu_mulai < DATE_TRUNC('month',CURRENT_DATE)+INTERVAL '1 month'");$s->execute([$r['id']]);$r['upah_lembur']=$s->fetchColumn();$r['total_upah']=(float)$r['upah_produksi']+(float)$r['upah_lembur'];}unset($r);
function rp($v){return 'Rp '.number_format((float)$v,0,',','.');} function kg($v){return number_format((float)$v,2,',','.').' kg';}
?>
<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Rekap Upah - Akunting</title><link href="../assets/css/bootstrap.min.css" rel="stylesheet"><style>body{background:#f8f9fa}.sidebar{min-height:100vh;background:#fff;border-right:1px solid #ddd}.brand{color:#198754;font-weight:700}.nav-link{color:#555;border-radius:8px;margin:3px 10px}.nav-link:hover,.nav-link.active{background:#198754;color:#fff}.content{padding:25px}.card{border:0;border-radius:12px}</style></head><body><div class="container-fluid"><div class="row"><aside class="col-md-3 col-lg-2 sidebar p-3"><h5 class="brand mb-4">🍤 Pabrik Udang</h5><small class="text-muted px-2">AKUNTING</small><nav class="mt-2"><a class="nav-link" href="dashboard_akunting.php">Dashboard</a><a class="nav-link" href="rekap_produksi.php">Rekap Produksi</a><a class="nav-link active" href="rekap_upah.php">Rekap Upah</a><a class="nav-link" href="histori_produksi_akunting.php">Histori Transaksi</a><a class="nav-link" href="master_tarif.php">Master Tarif</a><a class="nav-link" href="rekap_lembur.php">Rekap Lembur</a><a class="nav-link" href="profil_akunting.php">Profil Akunting</a><a class="nav-link" href="../logout.php">Logout</a></nav></aside><main class="col-md-9 col-lg-10 content"><div class="d-flex justify-content-between align-items-center mb-4"><div><h3 class="fw-bold mb-1">Rekap Upah Karyawan</h3><p class="text-muted mb-0">Produksi + lembur per karyawan.</p></div><form><select name="periode" class="form-select" onchange="this.form.submit()"><option value="hari" <?=$periode==='hari'?'selected':''?>>Hari Ini</option><option value="minggu" <?=$periode==='minggu'?'selected':''?>>Minggu Ini</option><option value="bulan" <?=$periode==='bulan'?'selected':''?>>Bulan Ini</option><option value="tahun" <?=$periode==='tahun'?'selected':''?>>Tahun Ini</option></select></form></div><div class="card shadow-sm"><div class="card-body"><div class="table-responsive"><table class="table table-hover align-middle"><thead class="table-light"><tr><th>No</th><th>Karyawan</th><th>Shift</th><th>Produksi</th><th>Upah Produksi</th><th>Upah Lembur*</th><th>Total Upah</th></tr></thead><tbody><?php $no=1;foreach($rows as $r): ?><tr><td><?=$no++?></td><td><b><?=htmlspecialchars($r['nama_lengkap'])?></b><br><small class="text-muted"><?=htmlspecialchars($r['barcode_uid'])?></small></td><td><?=htmlspecialchars($r['grup_shift']??'-')?></td><td><?=kg($r['total_kg'])?></td><td><?=rp($r['upah_produksi'])?></td><td><?=rp($r['upah_lembur'])?></td><td class="fw-bold"><?=rp($r['total_upah'])?></td></tr><?php endforeach;if(!$rows): ?><tr><td colspan="7" class="text-center text-muted py-4">Belum ada data.</td></tr><?php endif; ?></tbody></table></div><small class="text-muted">* Upah lembur pada halaman ini menggunakan data lembur bulan berjalan.</small></div></div></main></div></div></body></html>
